import { jsPDF } from "jspdf";

export function exportTextAsPdf(title: string, sections: { heading: string; body: string }[]) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const width = doc.internal.pageSize.getWidth() - margin * 2;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(title, margin, y);
  y += 26;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(`Generated by AI Productivity Copilot Pro · ${new Date().toLocaleString()}`, margin, y);
  y += 24;
  doc.setTextColor(20);

  for (const s of sections) {
    if (y > 760) { doc.addPage(); y = margin; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(s.heading, margin, y);
    y += 18;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(s.body || "—", width);
    for (const line of lines) {
      if (y > 780) { doc.addPage(); y = margin; }
      doc.text(line, margin, y);
      y += 15;
    }
    y += 12;
  }

  doc.save(`${title.replace(/[^a-z0-9-_ ]/gi, "").slice(0, 60)}.pdf`);
}
